---
# tasks file for ops_tools

- name: Copy Ops Tools
  copy: src={{ item }} dest=/{{ item }} owner=root group=root mode=0755
  with_items:
    - usr/local/bin/usereport.py


## Ubuntu

- block:
  - name: Add Sysdig Repository Key
    apt_key: url=https://s3.amazonaws.com/download.draios.com/DRAIOS-GPG-KEY.public state=present
    when: '"sysdig" in _ops_tools.tools'

  - name: Add Sysdig Repositories
    get_url: url=http://download.draios.com/stable/deb/draios.list dest=/etc/apt/sources.list.d/draios.list mode=0440
    register: add_sysdig_repo
    when: '"sysdig" in _ops_tools.tools'

  - name: Update APT Cache
    apt: update_cache=yes
    when: '"sysdig" in _ops_tools.tools and add_sysdig_repo|changed'

  - name: Install Ops Tools
    apt: name={{ item }} state=present
    with_items: "{{ _ops_tools.tools }}"

  when: "{{ ansible_distribution == 'Ubuntu' }}"


## ipkg

- block:
  - name: Check if ipkg is installed
    command: /opt/bin/ipkg --version
    register: ipkg
    always_run: true
    failed_when: ipkg|failed

  - name: Install Ops Tools
    command: /opt/bin/ipkg install {{ item }}
    with_items: "{{ _ops_tools.tools }}"
    when: ipkg|success

  when: "{{  ansible_cmdline.syno_hw_version is defined }}"

