---
# tasks file for ops_tools

- name: Copy Ops Tools
  copy: src={{ item }} dest=/{{ item }} owner=root group=root mode=0755
  with_items:
    - usr/local/bin/usereport.py


## Ubuntu

- block:
  - name: Add Repository Key URL
    apt_key: url="{{ item.key_url }}" state=present
    when: item.key_url is defined
    with_items: "{{ _ops_tools.apt_repos }}"
    register: new_keys

  - name: Add Repositories URL
    apt_repository: repo="{{ item.repo_line }}" state=present update_cache=no
    when: item.repo_line is defined
    with_items: "{{ _ops_tools.apt_repos }}"
    register: new_repos

  - name: Add Repositories PPA
    apt_repository: repo="{{ item.ppa }}" state=present update_cache=no
    when: item.ppa is defined
    with_items: "{{ _ops_tools.apt_repos }}"
    register: new_ppas

  - name: Update APT Cache
    apt: update_cache=yes
    when: new_keys|changed or new_repos|changed or new_ppas|changed

  - name: Install Ops Tools
    apt: name="{{ item }}" state=present
    with_items: "{{ _ops_tools.tools }}"

  when: "{{ ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian' }}"


## ipkg

- block:
  - name: Check if ipkg is installed
    command: /opt/bin/ipkg --version
    register: ipkg
    check_mode: false
    failed_when: ipkg|failed

  - name: Install Ops Tools
    command: /opt/bin/ipkg install {{ item }}
    with_items: "{{ _ops_tools.tools }}"
    when: ipkg|success

  when: "{{  ansible_cmdline.syno_hw_version is defined }}"

