# vim: ft=ansible et ts=2
---
- name: Add Repository Credentials
  ansible.builtin.copy:
    content: "machine {{ item.machine }} login {{ item.login }} password {{ item.password }}"
    dest: "/etc/apt/auth.conf.d/{{ item.name }}.conf"
    mode: "0640"
    owner: root
    group: root
  when: item.name is defined
  with_items: "{{ _ops_tools.repo_credentials | default([]) }}"

- name: Add Deb822 Repo
  ansible.builtin.deb822_repository:
    name: "{{ item.name }}"
    types: deb
    uris: "{{ item.uris }}"
    suites: "{{ item.suites }}"
    components: "{{ item.components }}"
    signed_by: "{{ item.signed_by }}"
  when: item.name is defined
  with_items: "{{ _ops_tools.deb822_repository | default([]) }}"

- name: Install Packages
  ansible.builtin.apt:
    state: present
    name: "{{ _ops_tools.packages }}"
    update_cache: true
